/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema_de_gerenciamento;

import java.awt.Color;
import java.awt.Container;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author Rafael
 */
public class ImprimirRecibo extends javax.swing.JFrame {

    /**
     * Creates new form ImprimirRecibo
     */
    public ImprimirRecibo() {
        initComponents();
        getRegistro();
        Container c = getContentPane();
        c.setBackground(new Color(0,153,153));
        
    }
    
    public void getRegistro(){
    
        try {
            Connection con = BDConexao.getConnection();
            PreparedStatement pst = con.prepareStatement("select * from fees_details order by reciept_no desc fetch first 1 rows only");
            ResultSet rs = pst.executeQuery();
            rs.next();
            txt_numeroRecibo.setText(rs.getString("reciept_no"));
            txt_modoDePagamento.setText(rs.getString("payment_mode"));
            
            String paymentMode = rs.getString("payment_mode");
            
            if (paymentMode.equalsIgnoreCase("Dinheiro")) {
                lbl_cheque_dd.setText("Cheque No ");
                txt_numeroCheque.setText("-");
                txt_nomeBanco.setText("-"); 
            }
            if (paymentMode.equalsIgnoreCase("Cheque")) {
                lbl_cheque_dd.setText("Cheque No ");
                txt_numeroCheque.setText(rs.getString("cheque_no"));
                txt_nomeBanco.setText(rs.getString("bank_name")); 
            }
            if (paymentMode.equalsIgnoreCase("dd")) {
                lbl_cheque_dd.setText("DD No ");
                txt_numeroCheque.setText(rs.getString("dd_no"));
                txt_nomeBanco.setText(rs.getString("bank_name")); 
            }
            if (paymentMode.equalsIgnoreCase("Cartão")) {
                lbl_cheque_dd.setText("Cheque No ");
                txt_numeroCheque.setText(rs.getString("-"));
                txt_nomeBanco.setText(rs.getString("bank_name")); 
            }
            
            txt_ReceboDo.setText(rs.getString("student_name"));
            txt_gstin.setText(rs.getString("gstin"));
            txt_primeiroAno.setText(rs.getString("year1"));
            txt_segundoAno.setText(rs.getString("year2"));
            
            txt_quantidadeInicial.setText(rs.getString("amount"));
            txt_cgst.setText(rs.getString("cgst"));
            txt_sgst.setText(rs.getString("sgst"));
            txt_total.setText(rs.getString("total_amount"));
            txt_totalEmDinheiro.setText(rs.getString("total_in_words"));
            txt_observacao.setText(rs.getString("remark"));
            txt_nomeCurso.setText(rs.getString("course_name"));
            
            
            
        } catch (Exception e) {
                e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelsidebar = new javax.swing.JPanel();
        panelPesquisarRegistro = new javax.swing.JPanel();
        btnpesquisarRegistro = new javax.swing.JLabel();
        panelEditarCurso = new javax.swing.JPanel();
        btnEditarCurso = new javax.swing.JLabel();
        panelListadeCursos = new javax.swing.JPanel();
        btnListadeCursos = new javax.swing.JLabel();
        panelTodosRegistros = new javax.swing.JPanel();
        btnTodososRegistros = new javax.swing.JLabel();
        panelVoltar = new javax.swing.JPanel();
        btnVoltar = new javax.swing.JLabel();
        panelInicio6 = new javax.swing.JPanel();
        btnInicio6 = new javax.swing.JLabel();
        panelEditar = new javax.swing.JPanel();
        btn_editar = new javax.swing.JLabel();
        panelSair = new javax.swing.JPanel();
        btnSair = new javax.swing.JLabel();
        panelImprimirRecibo = new javax.swing.JPanel();
        btn_impimir = new javax.swing.JLabel();
        painel_imprimir = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtprimeiroo = new javax.swing.JLabel();
        txt_nomeBanco = new javax.swing.JLabel();
        txt_numeroCheque = new javax.swing.JLabel();
        txt_modoDePagamento = new javax.swing.JLabel();
        txt_numeroRecibo = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_cheque_dd = new javax.swing.JLabel();
        lbl_nomeBanco = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_ReceboDo = new javax.swing.JLabel();
        txt_segundoAno = new javax.swing.JLabel();
        txt_primeiroAno = new javax.swing.JLabel();
        txt_gstin = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_total = new javax.swing.JLabel();
        lblcgst = new javax.swing.JLabel();
        lblsgst = new javax.swing.JLabel();
        txt_sgst = new javax.swing.JLabel();
        txt_quantidadeInicial = new javax.swing.JLabel();
        txt_cgst = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txt_nomeCurso = new javax.swing.JLabel();
        txt_totalEmDinheiro = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txt_observacao = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelsidebar.setBackground(new java.awt.Color(0, 102, 102));
        panelsidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPesquisarRegistro.setBackground(new java.awt.Color(0, 102, 102));
        panelPesquisarRegistro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelPesquisarRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnpesquisarRegistro.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnpesquisarRegistro.setForeground(new java.awt.Color(255, 255, 255));
        btnpesquisarRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema_de_gerenciamento/imagens/search2.png"))); // NOI18N
        btnpesquisarRegistro.setText("Pesquisar Registro");
        btnpesquisarRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpesquisarRegistroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnpesquisarRegistroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnpesquisarRegistroMouseExited(evt);
            }
        });
        panelPesquisarRegistro.add(btnpesquisarRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 360, 70));

        panelsidebar.add(panelPesquisarRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 380, 70));

        panelEditarCurso.setBackground(new java.awt.Color(0, 102, 102));
        panelEditarCurso.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelEditarCurso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEditarCurso.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnEditarCurso.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema_de_gerenciamento/imagens/edit2.png"))); // NOI18N
        btnEditarCurso.setText("Editar curso");
        btnEditarCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarCursoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarCursoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarCursoMouseExited(evt);
            }
        });
        panelEditarCurso.add(btnEditarCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 360, 70));

        panelsidebar.add(panelEditarCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 380, 70));

        panelListadeCursos.setBackground(new java.awt.Color(0, 102, 102));
        panelListadeCursos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelListadeCursos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnListadeCursos.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnListadeCursos.setForeground(new java.awt.Color(255, 255, 255));
        btnListadeCursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema_de_gerenciamento/imagens/list_1.png"))); // NOI18N
        btnListadeCursos.setText("Lista de Cursos");
        btnListadeCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListadeCursosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnListadeCursosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnListadeCursosMouseExited(evt);
            }
        });
        panelListadeCursos.add(btnListadeCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 360, 70));

        panelsidebar.add(panelListadeCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 380, 70));

        panelTodosRegistros.setBackground(new java.awt.Color(0, 102, 102));
        panelTodosRegistros.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelTodosRegistros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTodososRegistros.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnTodososRegistros.setForeground(new java.awt.Color(255, 255, 255));
        btnTodososRegistros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema_de_gerenciamento/imagens/view all record.png"))); // NOI18N
        btnTodososRegistros.setText("Ver Todos os Registros");
        btnTodososRegistros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTodososRegistrosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTodososRegistrosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTodososRegistrosMouseExited(evt);
            }
        });
        panelTodosRegistros.add(btnTodososRegistros, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 360, 70));

        panelsidebar.add(panelTodosRegistros, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 380, 70));

        panelVoltar.setBackground(new java.awt.Color(0, 102, 102));
        panelVoltar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelVoltar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVoltar.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema_de_gerenciamento/imagens/left-arrow.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoltarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVoltarMouseExited(evt);
            }
        });
        panelVoltar.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 360, 70));

        panelsidebar.add(panelVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 380, 70));

        panelInicio6.setBackground(new java.awt.Color(0, 102, 102));
        panelInicio6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelInicio6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInicio6.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnInicio6.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema_de_gerenciamento/imagens/home.png"))); // NOI18N
        btnInicio6.setText("  Inicio");
        btnInicio6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInicio6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInicio6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInicio6MouseExited(evt);
            }
        });
        panelInicio6.add(btnInicio6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 360, 70));

        panelsidebar.add(panelInicio6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 380, 70));

        panelEditar.setBackground(new java.awt.Color(0, 102, 102));
        panelEditar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelEditar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_editar.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btn_editar.setForeground(new java.awt.Color(255, 255, 255));
        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema_de_gerenciamento/imagens/edit2.png"))); // NOI18N
        btn_editar.setText("Editar");
        btn_editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_editarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_editarMouseExited(evt);
            }
        });
        panelEditar.add(btn_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 360, 70));

        panelsidebar.add(panelEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, 380, 70));

        panelSair.setBackground(new java.awt.Color(0, 102, 102));
        panelSair.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelSair.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSair.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema_de_gerenciamento/imagens/logout.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSairMouseExited(evt);
            }
        });
        panelSair.add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 360, 70));

        panelsidebar.add(panelSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 380, 70));

        panelImprimirRecibo.setBackground(new java.awt.Color(0, 102, 102));
        panelImprimirRecibo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelImprimirRecibo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_impimir.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btn_impimir.setForeground(new java.awt.Color(255, 255, 255));
        btn_impimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema_de_gerenciamento/imagens/printer-.png"))); // NOI18N
        btn_impimir.setText("Imprimir Recibo");
        btn_impimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_impimirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_impimirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_impimirMouseExited(evt);
            }
        });
        panelImprimirRecibo.add(btn_impimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 360, 70));

        panelsidebar.add(panelImprimirRecibo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 380, 70));

        getContentPane().add(panelsidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 730));

        painel_imprimir.setBackground(new java.awt.Color(255, 255, 255));
        painel_imprimir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        jLabel10.setText("Endereço");
        painel_imprimir.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 35)); // NOI18N
        jLabel9.setText("Nome Principal");
        painel_imprimir.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        jLabel13.setText("Nome Do Dono De Estabelecimento");
        painel_imprimir.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel11.setText("Nome Do  Estabelecimento");
        painel_imprimir.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema_de_gerenciamento/imagens/clg_1.png"))); // NOI18N
        painel_imprimir.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 160));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        painel_imprimir.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 780, 3));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Segue o pagamento na faculdade para o ano ");
        painel_imprimir.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        txtprimeiroo.setBackground(new java.awt.Color(0, 0, 0));
        txtprimeiroo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtprimeiroo.setText("-");
        painel_imprimir.add(txtprimeiroo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 10, -1));

        txt_nomeBanco.setBackground(new java.awt.Color(0, 0, 0));
        txt_nomeBanco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_nomeBanco.setText("Nome do Banco:");
        painel_imprimir.add(txt_nomeBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, -1, -1));

        txt_numeroCheque.setBackground(new java.awt.Color(0, 0, 0));
        txt_numeroCheque.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_numeroCheque.setText("Cheque no:");
        painel_imprimir.add(txt_numeroCheque, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, -1));

        txt_modoDePagamento.setBackground(new java.awt.Color(0, 0, 0));
        txt_modoDePagamento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_modoDePagamento.setText("Modo de Pagamento:");
        painel_imprimir.add(txt_modoDePagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        txt_numeroRecibo.setBackground(new java.awt.Color(0, 0, 0));
        txt_numeroRecibo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_numeroRecibo.setText("Numero de Recibo:");
        painel_imprimir.add(txt_numeroRecibo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Numero de Recibo:");
        painel_imprimir.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Modo de Pagamento:");
        painel_imprimir.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        lbl_cheque_dd.setBackground(new java.awt.Color(0, 0, 0));
        lbl_cheque_dd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_cheque_dd.setText("Cheque no:");
        painel_imprimir.add(lbl_cheque_dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        lbl_nomeBanco.setBackground(new java.awt.Color(0, 0, 0));
        lbl_nomeBanco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_nomeBanco.setText("Nome do Banco:");
        painel_imprimir.add(lbl_nomeBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Recibo do:");
        painel_imprimir.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        txt_ReceboDo.setBackground(new java.awt.Color(0, 0, 0));
        txt_ReceboDo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_ReceboDo.setText("Recibo do:");
        painel_imprimir.add(txt_ReceboDo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        txt_segundoAno.setBackground(new java.awt.Color(0, 0, 0));
        txt_segundoAno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_segundoAno.setText("2021");
        painel_imprimir.add(txt_segundoAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, -1, -1));

        txt_primeiroAno.setBackground(new java.awt.Color(0, 0, 0));
        txt_primeiroAno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_primeiroAno.setText("2020");
        painel_imprimir.add(txt_primeiroAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, -1, -1));

        txt_gstin.setBackground(new java.awt.Color(0, 0, 0));
        txt_gstin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_gstin.setText("GSTIN:");
        painel_imprimir.add(txt_gstin, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, -1, -1));

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("GSTIN:");
        painel_imprimir.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        painel_imprimir.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 780, 3));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        painel_imprimir.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 780, 10));

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Numero de serie:");
        painel_imprimir.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        jLabel22.setBackground(new java.awt.Color(0, 0, 0));
        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("Custos (taxas):");
        painel_imprimir.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, -1, -1));

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Quantidade:");
        painel_imprimir.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, -1, -1));

        txt_total.setBackground(new java.awt.Color(0, 0, 0));
        txt_total.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_total.setText("Total");
        painel_imprimir.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 530, -1, -1));

        lblcgst.setBackground(new java.awt.Color(0, 0, 0));
        lblcgst.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblcgst.setText("CGST (9 %)");
        painel_imprimir.add(lblcgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, -1, -1));

        lblsgst.setBackground(new java.awt.Color(0, 0, 0));
        lblsgst.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblsgst.setText("SGST (9 %)");
        painel_imprimir.add(lblsgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, -1, -1));

        txt_sgst.setBackground(new java.awt.Color(0, 0, 0));
        txt_sgst.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_sgst.setText("SGST 9 %");
        painel_imprimir.add(txt_sgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 490, -1, -1));

        txt_quantidadeInicial.setBackground(new java.awt.Color(0, 0, 0));
        txt_quantidadeInicial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_quantidadeInicial.setText("Heads:");
        painel_imprimir.add(txt_quantidadeInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 430, -1, -1));

        txt_cgst.setBackground(new java.awt.Color(0, 0, 0));
        txt_cgst.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_cgst.setText("CGST 9 %");
        painel_imprimir.add(txt_cgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 460, -1, -1));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        painel_imprimir.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 520, 220, 20));

        txt_nomeCurso.setBackground(new java.awt.Color(0, 0, 0));
        txt_nomeCurso.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_nomeCurso.setText("Heads:");
        painel_imprimir.add(txt_nomeCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, -1, -1));

        txt_totalEmDinheiro.setBackground(new java.awt.Color(0, 0, 0));
        txt_totalEmDinheiro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_totalEmDinheiro.setText("Total em dinheiro:");
        painel_imprimir.add(txt_totalEmDinheiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 580, -1, -1));

        jLabel24.setBackground(new java.awt.Color(0, 0, 0));
        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setText("Total em palavras:");
        painel_imprimir.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, -1, -1));

        txt_observacao.setBackground(new java.awt.Color(0, 0, 0));
        txt_observacao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_observacao.setText("Observação:");
        painel_imprimir.add(txt_observacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 610, -1, -1));

        jLabel23.setBackground(new java.awt.Color(0, 0, 0));
        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setText("Observação:");
        painel_imprimir.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        painel_imprimir.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 650, 220, 20));

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Assinatura do Remetente:");
        painel_imprimir.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 650, -1, -1));

        getContentPane().add(painel_imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 780, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnpesquisarRegistroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpesquisarRegistroMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(0,153,153);
        panelPesquisarRegistro.setBackground(clr);
    }//GEN-LAST:event_btnpesquisarRegistroMouseEntered

    private void btnpesquisarRegistroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpesquisarRegistroMouseExited
        Color clr = new Color(0,103,103);
        panelPesquisarRegistro.setBackground(clr);

    }//GEN-LAST:event_btnpesquisarRegistroMouseExited

    private void btnEditarCursoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarCursoMouseEntered
        Color clr = new Color(0,153,153);
        panelEditarCurso.setBackground(clr);
    }//GEN-LAST:event_btnEditarCursoMouseEntered

    private void btnEditarCursoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarCursoMouseExited
        Color clr = new Color(0,103,103);
        panelEditarCurso.setBackground(clr);
    }//GEN-LAST:event_btnEditarCursoMouseExited

    private void btnListadeCursosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListadeCursosMouseEntered
        Color clr = new Color(0,153,153);
        panelListadeCursos.setBackground(clr);
    }//GEN-LAST:event_btnListadeCursosMouseEntered

    private void btnListadeCursosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListadeCursosMouseExited
        Color clr = new Color(0,103,103);
        panelListadeCursos.setBackground(clr);
    }//GEN-LAST:event_btnListadeCursosMouseExited

    private void btnTodososRegistrosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTodososRegistrosMouseEntered
        Color clr = new Color(0,153,153);
        panelTodosRegistros.setBackground(clr);
    }//GEN-LAST:event_btnTodososRegistrosMouseEntered

    private void btnTodososRegistrosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTodososRegistrosMouseExited
        Color clr = new Color(0,103,103);
        panelTodosRegistros.setBackground(clr);
    }//GEN-LAST:event_btnTodososRegistrosMouseExited

    private void btnVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseEntered
        Color clr = new Color(0,153,153);
        panelVoltar.setBackground(clr);
    }//GEN-LAST:event_btnVoltarMouseEntered

    private void btnVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseExited
        Color clr = new Color(0,103,103);
        panelVoltar.setBackground(clr);
    }//GEN-LAST:event_btnVoltarMouseExited

    private void btnInicio6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicio6MouseEntered
        Color clr = new Color(0,153,153);
        panelInicio6.setBackground(clr);
    }//GEN-LAST:event_btnInicio6MouseEntered

    private void btnInicio6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicio6MouseExited
        Color clr = new Color(0,103,103);
        panelInicio6.setBackground(clr);
    }//GEN-LAST:event_btnInicio6MouseExited

    private void btn_editarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editarMouseEntered
        Color clr = new Color(0,153,153);
        panelEditar.setBackground(clr);
    }//GEN-LAST:event_btn_editarMouseEntered

    private void btn_editarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editarMouseExited
        Color clr = new Color(0,103,103);
        panelEditar.setBackground(clr);
    }//GEN-LAST:event_btn_editarMouseExited

    private void btnSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseEntered
        Color clr = new Color(0,153,153);
        panelSair.setBackground(clr);
    }//GEN-LAST:event_btnSairMouseEntered

    private void btnSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseExited
        Color clr = new Color(0,103,103);
        panelSair.setBackground(clr);
    }//GEN-LAST:event_btnSairMouseExited

    private void btn_impimirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_impimirMouseEntered
        Color clr = new Color(0,153,153);
        panelImprimirRecibo.setBackground(clr);
    }//GEN-LAST:event_btn_impimirMouseEntered

    private void btn_impimirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_impimirMouseExited
        Color clr = new Color(0,103,103);
        panelImprimirRecibo.setBackground(clr);
    }//GEN-LAST:event_btn_impimirMouseExited

    private void btn_impimirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_impimirMouseClicked
       
        PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");
            
            job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                 if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.77,0.77);//0.47,0.47
                
                painel_imprimir.print(g2);
         
               
                return Printable.PAGE_EXISTS;
                         
                
            }
    });
            boolean ok = job.printDialog();
        if(ok){
        try{
            
        job.print();
        }
        catch (PrinterException ex){
	ex.printStackTrace();
}
        }
        
        
    }//GEN-LAST:event_btn_impimirMouseClicked

    private void btn_editarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editarMouseClicked
       
        AtualizarTaxasDetalhes atualizar = new AtualizarTaxasDetalhes();
        atualizar.setVisible(true);
        this.dispose();
        
// TODO add your handling code here:
    }//GEN-LAST:event_btn_editarMouseClicked

    private void btnpesquisarRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpesquisarRegistroMouseClicked
        PesquisarRegistros pqsRegistro = new PesquisarRegistros();
        pqsRegistro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnpesquisarRegistroMouseClicked

    private void btnInicio6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicio6MouseClicked
        Pagina_inicial pgInicial = new Pagina_inicial();
        pgInicial.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInicio6MouseClicked

    private void btnEditarCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarCursoMouseClicked
         EditarCurso edtCurso = new EditarCurso();
        edtCurso.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEditarCursoMouseClicked

    private void btnTodososRegistrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTodososRegistrosMouseClicked
        VerRegistros verregistros = new VerRegistros();
        verregistros.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTodososRegistrosMouseClicked

    private void btnListadeCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListadeCursosMouseClicked
        EditarCurso edtCurso = new EditarCurso();
        edtCurso.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnListadeCursosMouseClicked

    private void btnVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseClicked
        Pagina_inicial pgInicial = new Pagina_inicial();
        pgInicial.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarMouseClicked

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImprimirRecibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImprimirRecibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImprimirRecibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImprimirRecibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImprimirRecibo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnEditarCurso;
    private javax.swing.JLabel btnInicio6;
    private javax.swing.JLabel btnListadeCursos;
    private javax.swing.JLabel btnSair;
    private javax.swing.JLabel btnTodososRegistros;
    private javax.swing.JLabel btnVoltar;
    private javax.swing.JLabel btn_editar;
    private javax.swing.JLabel btn_impimir;
    private javax.swing.JLabel btnpesquisarRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lbl_cheque_dd;
    private javax.swing.JLabel lbl_nomeBanco;
    private javax.swing.JLabel lblcgst;
    private javax.swing.JLabel lblsgst;
    private javax.swing.JPanel painel_imprimir;
    private javax.swing.JPanel panelEditar;
    private javax.swing.JPanel panelEditarCurso;
    private javax.swing.JPanel panelImprimirRecibo;
    private javax.swing.JPanel panelInicio6;
    private javax.swing.JPanel panelListadeCursos;
    private javax.swing.JPanel panelPesquisarRegistro;
    private javax.swing.JPanel panelSair;
    private javax.swing.JPanel panelTodosRegistros;
    private javax.swing.JPanel panelVoltar;
    private javax.swing.JPanel panelsidebar;
    private javax.swing.JLabel txt_ReceboDo;
    private javax.swing.JLabel txt_cgst;
    private javax.swing.JLabel txt_gstin;
    private javax.swing.JLabel txt_modoDePagamento;
    private javax.swing.JLabel txt_nomeBanco;
    private javax.swing.JLabel txt_nomeCurso;
    private javax.swing.JLabel txt_numeroCheque;
    private javax.swing.JLabel txt_numeroRecibo;
    private javax.swing.JLabel txt_observacao;
    private javax.swing.JLabel txt_primeiroAno;
    private javax.swing.JLabel txt_quantidadeInicial;
    private javax.swing.JLabel txt_segundoAno;
    private javax.swing.JLabel txt_sgst;
    private javax.swing.JLabel txt_total;
    private javax.swing.JLabel txt_totalEmDinheiro;
    private javax.swing.JLabel txtprimeiroo;
    // End of variables declaration//GEN-END:variables
}
